name: Deploy Terraform

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Nom de l’environnement (ex: dev, staging, prod)'
        required: true
        default: 'dev'

jobs:
  terraform_deploy:
    runs-on: ubuntu-latest
    name: Terraform Deploy to Azure

    env:  # Export global pour tous les steps (Terraform + az CLI)
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      AZURE_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure CLI Login (service principal)
        run: |
          echo "🔐 Connexion Azure CLI via service principal..."
          az login --service-principal \
            --username "$SP_ID" \
            --password "$SP_SECRET" \
            --tenant "$TENANT_ID"
          az account show
        env:
          SP_ID: ${{ secrets.ARM_CLIENT_ID }}
          SP_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Terraform Init (backend dynamique)
        run: |
          terraform init \
            -backend-config="resource_group_name=rg-terraform-state" \
            -backend-config="storage_account_name=stterraformstatedevops" \
            -backend-config="container_name=tfstate" \
            -backend-config="key=devops-cicd.tfstate"

      - name: Terraform Plan
        run: |
          terraform plan -var="environment=${{ github.event.inputs.environment }}"

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve -var="environment=${{ github.event.inputs.environment }}"
