name: Deploy Terraform

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Nom de l’environnement (ex: dev, staging, prod)'
        required: true
        default: 'dev'

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  terraform_deploy:
    runs-on: ubuntu-latest
    name: Terraform Deploy to Azure

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        run: |
          export ARM_CLIENT_ID=$ARM_CLIENT_ID
          export ARM_CLIENT_SECRET=$ARM_CLIENT_SECRET
          export ARM_SUBSCRIPTION_ID=$ARM_SUBSCRIPTION_ID
          export ARM_TENANT_ID=$ARM_TENANT_ID
    
          terraform init 

      - name: Terraform Plan
        run: |
          terraform plan -var="environment=${{ github.event.inputs.environment }}"

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve -var="environment=${{ github.event.inputs.environment }}"
