name: Deploy Terraform

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Nom de l''environnement (ex: dev, staging, prod)'
        required: true
        default: 'dev'

jobs:
  terraform_deploy:
    runs-on: ubuntu-latest
    name: Terraform Deploy to Azure


    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      TF_VAR_github_username: ${{ secrets.TF_VAR_GITHUB_USERNAME }}
      TF_VAR_github_token: ${{ secrets.TF_VAR_GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure CLI Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: Terraform Init
        run: terraform init 
        
      - name: Terraform Import Resource Group
        run: terraform import azurerm_resource_group.terraform_state "/subscriptions/${{ env.ARM_SUBSCRIPTION_ID }}/resourceGroups/rg-terraform-state"

      - name: Terraform Refresh
        run: terraform refresh

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var="environment=${{ github.event.inputs.environment }}"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="environment=${{ github.event.inputs.environment }}"
